tf) marcos@doutor:~/GIT/OracleStock$ ./src/run.sh 
Using TensorFlow backend.
ABCB4.SA
2020-07-19 23:49:36.440427: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-19 23:49:36.441546: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5670e80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 23:49:36.441658: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 24.654745119240804
LSTM: 2.8325079013773045
CNN-LSTM: 2.5422138231460853
ConvLSTM2D: 4.005329183073672
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
ABEV3.SA
CNN: 76.11030295426453
LSTM: 37.85475574684799
CNN-LSTM: 11.691778830131732
ConvLSTM2D: 14.960349576309362
AMAR3.SA
CNN: 37.42829639170298
LSTM: 9.594977488938648
CNN-LSTM: 15.818506076981267
ConvLSTM2D: 12.083843319358094
ARZZ3.SA
CNN: 27.510258419758927
LSTM: 2.1087680559409963
CNN-LSTM: 2.6564998462224465
ConvLSTM2D: 2.593401678844927
AZUL4.SA
CNN: 27.397232181268432
LSTM: 12.172697182009568
CNN-LSTM: 9.69999403274127
ConvLSTM2D: 9.203806179920186
B3SA3.SA
CNN: 42.24000406636186
LSTM: 14.121028134423765
CNN-LSTM: 8.797844487493874
ConvLSTM2D: 7.598558205011435
BBAS3.SA
CNN: 16.758342889153514
LSTM: 15.386148357120172
CNN-LSTM: 1.9896746157777356
ConvLSTM2D: 16.361613757152536
BBDC3.SA
CNN: 2.6784621113475975
LSTM: 11.677911557880735
CNN-LSTM: 4.193118299594441
ConvLSTM2D: 4.32975771748815
BBDC3.SA
/home/marcos/tf/lib/python3.7/site-packages/keras/callbacks/callbacks.py:95: RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.263402). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)
CNN: 19.096413212656536
LSTM: 17.643142465265438
CNN-LSTM: 6.552340999945419
ConvLSTM2D: 9.222285066977701
BBSE3.SA
CNN: 3.6053317850045903
LSTM: 53.2073404500266
CNN-LSTM: 39.86114616176421
ConvLSTM2D: 43.64544202225715
python: no process found
Using TensorFlow backend.
B3SA3.SA
2020-07-20 00:45:57.708298: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 00:45:57.709425: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x591fe80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 00:45:57.709563: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 39.794453185982874
LSTM: 8.700199191463435
CNN-LSTM: 9.537795189786934
ConvLSTM2D: 8.593624206509036
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
BBAS3.SA
CNN: 18.465681013174066
LSTM: 3.9573225705130084
CNN-LSTM: 5.836994044273709
ConvLSTM2D: 11.770131594635002
BBDC3.SA
CNN: 15.072949370356062
LSTM: 14.752261025581573
CNN-LSTM: 4.215859663188747
ConvLSTM2D: 10.80232104709628
BBDC3.SA
CNN: 11.362310490311126
LSTM: 12.519568808558798
CNN-LSTM: 9.622138824640182
ConvLSTM2D: 12.227836339025094
BBSE3.SA
CNN: 3.4311003010597396
LSTM: 51.58487519361786
CNN-LSTM: 20.94406474721702
ConvLSTM2D: 32.22865359266903
BEEF3.SA
CNN: 33.91476186225099
LSTM: 3.7747144488549274
CNN-LSTM: 3.6428943994436227
ConvLSTM2D: 3.314457333680812
BIDI3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
BEEF3.SA
2020-07-20 01:05:18.096858: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 01:05:18.098925: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4df2ea0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 01:05:18.099184: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 27.360322652563347
LSTM: 3.9048108526206016
CNN-LSTM: 3.314937304447637
ConvLSTM2D: 3.164949890879244
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
BIDI3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
BRDT3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
BTOW3.SA
2020-07-20 01:09:54.556392: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 01:09:54.556984: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5215960 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 01:09:54.557016: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 40.64517661781287
LSTM: 59.73218610505272
CNN-LSTM: 40.60264470804889
ConvLSTM2D: 22.496425648401182
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
CAML3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
CIEL3.SA
2020-07-20 01:12:24.104399: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 01:12:24.105123: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x50f91c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 01:12:24.105166: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 451.48264604126524
LSTM: 365.98053360004997
CNN-LSTM: 163.27844156466105
ConvLSTM2D: 118.9543627342776
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
CMIG3.SA
CNN: 8.729316824366952
LSTM: 12.718237666783546
CNN-LSTM: 6.647017969205697
ConvLSTM2D: 5.348748196921196
CNTO3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
CPLE3.SA
2020-07-20 01:18:11.832352: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 01:18:11.833193: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x40c6590 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 01:18:11.833217: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 31.593466548782533
LSTM: 2.2369235122504647
CNN-LSTM: 1.9618945764536095
ConvLSTM2D: 9.416894565584899
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
CRFB3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 94, in model_conv1_FG
    y = y[:,:,-2:-1]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
python: no process found
Using TensorFlow backend.
CVCB3.SA
2020-07-20 01:21:24.508461: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 01:21:24.509299: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3f56e40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 01:21:24.509335: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 86.88880376431123
LSTM: 61.151654541083225
CNN-LSTM: 27.865823936063883
ConvLSTM2D: 42.92842064727178
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
CYRE3.SA
CNN: 38.730418900816765
LSTM: 5.207582950635644
CNN-LSTM: 4.44409268590523
ConvLSTM2D: 3.6782146011151817
DIRR3.SA
CNN: 43.96098490228544
LSTM: 4.973573935938391
CNN-LSTM: 2.279712422191785
ConvLSTM2D: 1.9375611881580097
ECOR3.SA
CNN: 27.2837916147738
LSTM: 5.246357649546773
CNN-LSTM: 4.03208797494166
ConvLSTM2D: 4.853132153126167
EGIE3.SA
CNN: 6.208691205206975
LSTM: 10.391461148401877
CNN-LSTM: 6.742556279168498
ConvLSTM2D: 20.52647938488367
ELET3.SA
CNN: 13.499143090239226
LSTM: 5.13995779030949
CNN-LSTM: 2.661127754535312
ConvLSTM2D: 5.291183588409589
ELET3.SA
CNN: 17.692615814558085
LSTM: 5.098319848672929
CNN-LSTM: 2.0872001450561095
ConvLSTM2D: 9.513343195666755
EMBR3.SA
CNN: 420.3066281042409
LSTM: 324.76147913587766
CNN-LSTM: 145.68687235754524
ConvLSTM2D: 109.62931404581542
ENAT3.SA
CNN: 11.036562297614596
LSTM: 18.219057721044233
CNN-LSTM: 2.36733990862135
ConvLSTM2D: 18.283418324368913
ENBR3.SA
CNN: 6.045921583152162
LSTM: 7.346839769262364
CNN-LSTM: 6.146665681474555
ConvLSTM2D: 7.528773773651213
python: no process found
Using TensorFlow backend.
ELET3.SA
2020-07-20 02:15:10.832434: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 02:15:10.834186: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ae8a70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 02:15:10.834302: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 16.561992682539827
LSTM: 5.124753189073227
CNN-LSTM: 2.4317478992551864
ConvLSTM2D: 6.520181504162706
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
ELET3.SA
CNN: 15.247230818347285
LSTM: 6.217680201817047
CNN-LSTM: 3.07165167514661
ConvLSTM2D: 6.4219307939303585
EMBR3.SA
CNN: 499.57538860556497
LSTM: 270.4454958147549
CNN-LSTM: 173.55075917961085
ConvLSTM2D: 63.33918216114718
ENAT3.SA
CNN: 3.671717211270104
LSTM: 16.58690228383045
CNN-LSTM: 3.7981980533050166
ConvLSTM2D: 18.007446181474176
ENBR3.SA
CNN: 15.173883349027854
LSTM: 9.360388660186109
CNN-LSTM: 11.657381309721536
ConvLSTM2D: 9.36149823272885
ENGI3.SA
CNN: 19.881451934284485
LSTM: 1.101945099335392
CNN-LSTM: 4.050806321617251
ConvLSTM2D: 2.0213148140640564
EVEN3.SA
CNN: 31.777688070584993
LSTM: 3.5959000813843853
CNN-LSTM: 3.16988897812279
ConvLSTM2D: 2.492317801897709
EQTL3.SA
CNN: 31.449340159278684
LSTM: 3.230122859912691
CNN-LSTM: 2.3633927920762945
ConvLSTM2D: 2.1337509837830537
EZTC3.SA
CNN: 22.607871740653874
LSTM: 5.597682391744018
CNN-LSTM: 7.186195403016754
ConvLSTM2D: 6.809521596760478
DTEX3.SA
CNN: 27.997019162112924
LSTM: 6.373818503428897
CNN-LSTM: 4.666438538675997
ConvLSTM2D: 3.7864528835139897
python: no process found
Using TensorFlow backend.
ENGI3.SA
2020-07-20 02:55:55.960718: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 02:55:55.964102: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5484130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 02:55:55.964500: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 24.105174211454035
LSTM: 2.661024197334599
CNN-LSTM: 2.1814280350466277
ConvLSTM2D: 4.302393385559701
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
EVEN3.SA
CNN: 44.29165374341094
LSTM: 5.2737014827232835
CNN-LSTM: 4.149441219947679
ConvLSTM2D: 3.8895135144341135
EQTL3.SA
CNN: 39.82510419208927
LSTM: 3.2528270404817623
CNN-LSTM: 2.881605369514302
ConvLSTM2D: 2.697679032808487
EZTC3.SA
CNN: 21.674360302069125
LSTM: 5.899416972302431
CNN-LSTM: 4.789944308040443
ConvLSTM2D: 4.843936990030624
DTEX3.SA
CNN: 27.717263009866677
LSTM: 5.823025098479924
CNN-LSTM: 7.70683794924117
ConvLSTM2D: 3.812761434114023
FLRY3.SA
CNN: 35.54620905379745
LSTM: 8.872522260403464
CNN-LSTM: 5.962667109377147
ConvLSTM2D: 4.37531575777146
GFSA3.SA
CNN: 3.946444262149715
LSTM: 5.267935425228684
CNN-LSTM: 3.519542865023844
ConvLSTM2D: 4.599117434755174
GGBR3.SA
CNN: 26.88355449847438
LSTM: 4.361804714694652
CNN-LSTM: 2.507555233360653
ConvLSTM2D: 9.2890790844882
GNDI3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
FLRY3.SA
2020-07-20 03:15:14.556535: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:15:14.557620: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x40a99c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:15:14.557667: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 36.29793410306387
LSTM: 5.207056169691891
CNN-LSTM: 4.159234174494024
ConvLSTM2D: 7.802384693058379
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
GFSA3.SA
CNN: 4.857021864090858
LSTM: 5.1976206031287955
CNN-LSTM: 5.24654525758981
ConvLSTM2D: 4.448211171051835
GGBR3.SA
CNN: 30.656896300502623
LSTM: 1.6422054138112343
CNN-LSTM: 3.0851733660630996
ConvLSTM2D: 11.529907402877248
GNDI3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
GOLL4.SA
2020-07-20 03:21:09.052413: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:21:09.053359: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4ffade0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:21:09.053376: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 23.66264778078997
LSTM: 4.257680251442051
CNN-LSTM: 3.9804167714648724
ConvLSTM2D: 6.844836536053165
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
HAPV3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
IRBR3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
KLBN11.SA
2020-07-20 03:24:23.336524: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:24:23.337228: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4a848e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:24:23.337275: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 24.272241749343195
LSTM: 16.133751969335858
CNN-LSTM: 3.6652963808186243
ConvLSTM2D: 25.337845832004547
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
LAME3.SA
CNN: 38.740874972791765
LSTM: 15.76314403540698
CNN-LSTM: 12.960556504075443
ConvLSTM2D: 6.211837068036618
LIGT3.SA
CNN: 20.012365220598234
LSTM: 3.3156315608878377
CNN-LSTM: 1.7820814306243296
ConvLSTM2D: 1.8918006443412898
LINX3.SA
CNN: 10.799653345383774
LSTM: 6.134771522609204
CNN-LSTM: 5.186197711479515
ConvLSTM2D: 5.754288306982687
LOGN3.SA
CNN: 27.359821831446162
LSTM: 4.7705741993532635
CNN-LSTM: 2.1301664822114104
ConvLSTM2D: 1.7770923483555838
LREN3.SA
CNN: 22.2695135177168
LSTM: 4.178486330885215
CNN-LSTM: 4.195887368503739
ConvLSTM2D: 7.234636720906824
LWSA3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
LREN3.SA
2020-07-20 03:43:09.440644: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:43:09.441959: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x54fc6e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:43:09.442012: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 24.0137273235794
LSTM: 3.4431059029696947
CNN-LSTM: 3.771796406367793
ConvLSTM2D: 5.500498835124986
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
LWSA3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
MRFG3.SA
2020-07-20 03:46:16.868445: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:46:16.869480: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5233ea0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:46:16.869523: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 44.91232396061454
LSTM: 8.084101119346654
CNN-LSTM: 10.383550747451082
ConvLSTM2D: 8.56201752490264
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
MRVE3.SA
CNN: 33.70282555004035
LSTM: 3.3797597630516525
CNN-LSTM: 2.730575565601202
ConvLSTM2D: 5.750903059397815
MULT3.SA
CNN: 11.216717326283113
LSTM: 6.31527270277331
CNN-LSTM: 5.712518225339334
ConvLSTM2D: 4.873140990887912
MYPK3.SA
CNN: 108.32969863057136
LSTM: 52.26897770677561
CNN-LSTM: 25.879742404301272
ConvLSTM2D: 22.97933507870698
NEOE3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
NTCO3.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
POMO3.SA
2020-07-20 03:55:37.308517: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 03:55:37.309091: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3e95400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 03:55:37.309133: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 8.250310590092278
LSTM: 8.715232239581129
CNN-LSTM: 5.351571103469706
ConvLSTM2D: 21.728250352959876
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
POSI3.SA
CNN: 6.685958641049335
LSTM: 28.638516804856078
CNN-LSTM: 16.403814040142397
ConvLSTM2D: 35.19892915220634
PRIO3.SA
CNN: 29.72091499452666
LSTM: 5.520610576569281
CNN-LSTM: 6.576479362322117
ConvLSTM2D: 5.859679160727457
QUAL3.SA
CNN: 28.730246217907258
LSTM: 5.431565693310085
CNN-LSTM: 4.366153288164747
ConvLSTM2D: 4.036830554208743
RADL3.SA
CNN: 29.85591197395837
LSTM: 2.4151178932529427
CNN-LSTM: 6.645735855109458
ConvLSTM2D: 2.4769990414359846
RAIL3.SA
CNN: 44.48663805576293
LSTM: 1.7278838222406563
CNN-LSTM: 2.3661499723331048
ConvLSTM2D: 1.876862210063713
RAPT3.SA
CNN: 23.275179664859735
LSTM: 10.023065401324288
CNN-LSTM: 2.1965738425282355
ConvLSTM2D: 11.0846060916016
RENT3.SA
CNN: 37.49531125861419
LSTM: 2.5032038877260345
CNN-LSTM: 3.81956977869501
ConvLSTM2D: 2.9186696646638643
SANB11.SA
CNN: 2.3332291675925805
LSTM: 13.040957147616709
CNN-LSTM: 3.8445570766942057
ConvLSTM2D: 4.431948137827248
SAPR11.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
RAIL3.SA
2020-07-20 04:22:26.500632: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 04:22:26.503349: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4a4de10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 04:22:26.503631: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 29.787465363909206
LSTM: 2.1017461724526454
CNN-LSTM: 3.2250478524361297
ConvLSTM2D: 2.391480247145752
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
RAPT3.SA
CNN: 24.89525058323586
LSTM: 9.402504979602025
CNN-LSTM: 2.023689229645294
ConvLSTM2D: 7.254785682085073
RENT3.SA
CNN: 29.662980688127437
LSTM: 4.917352272250904
CNN-LSTM: 2.724547142268326
ConvLSTM2D: 2.9728844974370836
SANB11.SA
CNN: 1.949914511663762
LSTM: 13.572199967500353
CNN-LSTM: 3.1549510826041347
ConvLSTM2D: 16.15343728997675
SAPR11.SA
Traceback (most recent call last):
  File "src/models_FG.py", line 682, in <module>
    model_conv1_FG(stock)
  File "src/models_FG.py", line 85, in model_conv1_FG
    dataset = scaler.fit_transform(data.ffill().values)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 336, in fit
    return self.partial_fit(X, y)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 371, in partial_fit
    force_all_finite="allow-nan")
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/marcos/tf/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by MinMaxScaler.
python: no process found
Using TensorFlow backend.
SBSP3.SA
2020-07-20 04:36:01.156524: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 04:36:01.157579: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x500a6c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 04:36:01.157617: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 41.149512539511846
LSTM: 2.2472389080208974
CNN-LSTM: 2.2521651506712907
ConvLSTM2D: 2.539707766361022
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
SMTO3.SA
CNN: 17.845699334716528
LSTM: 6.3590977569064195
CNN-LSTM: 7.449811424864445
ConvLSTM2D: 12.847819333447779
SULA3.SA
CNN: 27.670344508353896
LSTM: 7.815703335412519
CNN-LSTM: 4.48406796887447
ConvLSTM2D: 9.157863933947702
SUZB3.SA
CNN: 14.050563282391984
LSTM: 2.62143322169598
CNN-LSTM: 3.7254326750758597
ConvLSTM2D: 5.146293866520917
TCSA3.SA
CNN: 74.92318723144
LSTM: 220.58425376057338
CNN-LSTM: 50.15792639080184
ConvLSTM2D: 42.1794636725064
TAEE3.SA
CNN: 5.916505143566326
LSTM: 18.07428694519535
CNN-LSTM: 2.0793963174444863
ConvLSTM2D: 19.758431489065366
TIMP3.SA
CNN: 37.08343716085242
LSTM: 5.557193815691633
CNN-LSTM: 3.1879394450843845
ConvLSTM2D: 5.176292030051976
TOTS3.SA
CNN: 21.319854185834267
LSTM: 4.193672493107082
CNN-LSTM: 3.052354648766803
ConvLSTM2D: 3.9177472035917837
TRIS3.SA
CNN: 40.62317903328777
LSTM: 2.384312804777346
CNN-LSTM: 2.5326717117210342
ConvLSTM2D: 3.707625294306946
TUPY3.SA
CNN: 12.658398505000228
LSTM: 11.374555485251694
CNN-LSTM: 2.728075515990752
ConvLSTM2D: 9.126129142117929
python: no process found
Using TensorFlow backend.
TAEE3.SA
2020-07-20 05:08:55.152894: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 05:08:55.155213: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4403010 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 05:08:55.155436: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 15.75452616210741
LSTM: 18.545495240037955
CNN-LSTM: 2.343757456564673
ConvLSTM2D: 18.02969532515283
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
TIMP3.SA
CNN: 34.87907086834138
LSTM: 4.8122238809378794
CNN-LSTM: 2.8672145795556223
ConvLSTM2D: 3.8061036219404105
TOTS3.SA
CNN: 6.781410942732341
LSTM: 4.168808766085127
CNN-LSTM: 7.1719447574408655
ConvLSTM2D: 5.324755228341403
TRIS3.SA
CNN: 31.685998945563128
LSTM: 7.93822173796917
CNN-LSTM: 2.4218422836354216
ConvLSTM2D: 2.267298806764783
TUPY3.SA
CNN: 10.107043863323446
LSTM: 13.312716095255967
CNN-LSTM: 3.0303457581068156
ConvLSTM2D: 12.454844306481707
UGPA3.SA
CNN: 15.236181222301932
LSTM: 132.62702900477169
CNN-LSTM: 14.991561182858826
ConvLSTM2D: 21.25466663517009
UNIP6.SA
CNN: 9.38363971138005
LSTM: 13.813971699309539
CNN-LSTM: 13.637469363463753
ConvLSTM2D: 3.653686123914493
USIM5.SA
CNN: 22.416961613824935
LSTM: 1.8170022239790873
CNN-LSTM: 1.961499420227085
ConvLSTM2D: 2.1913525096627415
VALE3.SA
CNN: 31.802291988017213
LSTM: 6.5550324379107305
CNN-LSTM: 7.424267102042154
ConvLSTM2D: 9.034066398376522
VIVT3.SA
CNN: 30.690505412201418
LSTM: 9.055470523194394
CNN-LSTM: 12.949326006919403
ConvLSTM2D: 17.796489220521963
python: no process found
Using TensorFlow backend.
UGPA3.SA
2020-07-20 05:39:39.080789: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 05:39:39.083092: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3d934b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 05:39:39.083283: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 30.132387443579685
LSTM: 20.15863954658369
CNN-LSTM: 16.767147124514064
ConvLSTM2D: 20.8476846261
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
UNIP6.SA
CNN: 27.692237098159456
LSTM: 1.1871705833363746
CNN-LSTM: 6.043204998784706
ConvLSTM2D: 4.101587891573604
USIM5.SA
CNN: 13.617684670579019
LSTM: 3.668518713339506
CNN-LSTM: 1.7385993304116751
ConvLSTM2D: 3.136677783626257
VALE3.SA
CNN: 26.516735267747464
LSTM: 5.958052672122372
CNN-LSTM: 6.826458881096428
ConvLSTM2D: 10.33309010715076
VIVT3.SA
CNN: 28.889541161220013
LSTM: 11.569076013779302
CNN-LSTM: 7.796476401761243
ConvLSTM2D: 23.426487779503365
VLID3.SA
CNN: 233.35933201039012
LSTM: 158.044618493195
CNN-LSTM: 75.81480281958619
ConvLSTM2D: 44.67486752893047
VVAR3.SA
CNN: 43.40568762458454
LSTM: 5.89823088780724
CNN-LSTM: 4.412827664160938
ConvLSTM2D: 4.981116804878927
WEGE3.SA
CNN: 49.163256730084534
LSTM: 11.759718998596494
CNN-LSTM: 28.8021804335722
ConvLSTM2D: 13.125382992874366
WIZS3.SA
CNN: 27.394676730382255
LSTM: 74.59958545288717
CNN-LSTM: 81.54129370005842
ConvLSTM2D: 80.84157825486827
YDUQ3.SA
CNN: 28.065403867630405
LSTM: 3.6436535506657606
CNN-LSTM: 8.005396528447092
ConvLSTM2D: 2.837855554225826
python: no process found
Using TensorFlow backend.
VLID3.SA
2020-07-20 06:07:18.220721: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1800000000 Hz
2020-07-20 06:07:18.222638: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4be6140 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 06:07:18.222839: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
CNN: 223.0177775001897
LSTM: 119.45567654542093
CNN-LSTM: 78.3640994715579
ConvLSTM2D: 82.0265241233457
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
VVAR3.SA
CNN: 41.06429037919364
LSTM: 6.2748786316339595
CNN-LSTM: 4.654071050800274
ConvLSTM2D: 3.5537025759513208
WEGE3.SA
CNN: 42.69258912269573
LSTM: 46.211659751805804
CNN-LSTM: 30.367981981506897
ConvLSTM2D: 14.25156108056102
WIZS3.SA
CNN: 35.3787397946952
LSTM: 59.04468485704083
CNN-LSTM: 79.25868680759848
ConvLSTM2D: 91.28040066487905
YDUQ3.SA
CNN: 27.683994714823886
LSTM: 9.44991576009274
CNN-LSTM: 7.554998836015786
ConvLSTM2D: 4.214037649566187
python: no process found
(tf) marcos@doutor:~/GIT/OracleStock$ 
